export const columns = ['label','w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9', 'w10', 'w11', 'w12', 'w13', 'w14', 'w15']

export const mapData = [
    {label:'az',
    w1: 'dal',
    w2: 'chi',
    w3: 'lv',
    w4: 'lar',
    w5: 'lac',
    w6: 'wsh',
    w7: 'dal',
    w8: 'mia',
    w9: 'ne',
    w10: 'no',
    w11: 'dal',
    w12: 'pit',
    w13: 'dal',
    w14: 'cin',
    w15: 'cle'}
    ,
    {label:'det',
    w1: 'sf',
    w2: 'gb',
    w3: 'bal',
    w4: 'chi',
    w5: 'min',
    w6: 'cin',
    w7: 'phi',
    w8: 'lac',
    w9: 'min',
    w10: 'cle',
    w11: 'pit',
    w12: 'chi',
    w13: 'min',
    w14: 'den',
    w15: 'ari'},
    {label:'az',
    w1: 'dal',
    w2: 'chi',
    w3: 'lv',
    w4: 'lar',
    w5: 'lac',
    w6: 'wsh',
    w7: 'dal',
    w8: 'mia',
    w9: 'ne',
    w10: 'no',
    w11: 'dal',
    w12: 'pit',
    w13: 'dal',
    w14: 'cin',
    w15: 'cle'}
    ,
    {label:'det',
    w1: 'sf',
    w2: 'gb',
    w3: 'bal',
    w4: 'chi',
    w5: 'min',
    w6: 'cin',
    w7: 'phi',
    w8: 'lac',
    w9: 'min',
    w10: 'cle',
    w11: 'pit',
    w12: 'chi',
    w13: 'min',
    w14: 'den',
    w15: 'ari'},
    {label:'az',
    w1: 'dal',
    w2: 'chi',
    w3: 'lv',
    w4: 'lar',
    w5: 'lac',
    w6: 'wsh',
    w7: 'dal',
    w8: 'mia',
    w9: 'ne',
    w10: 'no',
    w11: 'dal',
    w12: 'pit',
    w13: 'dal',
    w14: 'cin',
    w15: 'cle'}
    ,
    {label:'det',
    w1: 'sf',
    w2: 'gb',
    w3: 'bal',
    w4: 'chi',
    w5: 'min',
    w6: 'cin',
    w7: 'phi',
    w8: 'lac',
    w9: 'min',
    w10: 'cle',
    w11: 'pit',
    w12: 'chi',
    w13: 'min',
    w14: 'den',
    w15: 'ari'},
    {label:'az',
    w1: 'dal',
    w2: 'chi',
    w3: 'lv',
    w4: 'lar',
    w5: 'lac',
    w6: 'wsh',
    w7: 'dal',
    w8: 'mia',
    w9: 'ne',
    w10: 'no',
    w11: 'dal',
    w12: 'pit',
    w13: 'dal',
    w14: 'cin',
    w15: 'cle'}
    ,
    {label:'det',
    w1: 'sf',
    w2: 'gb',
    w3: 'bal',
    w4: 'chi',
    w5: 'min',
    w6: 'cin',
    w7: 'phi',
    w8: 'lac',
    w9: 'min',
    w10: 'cle',
    w11: 'pit',
    w12: 'chi',
    w13: 'min',
    w14: 'den',
    w15: 'ari'},
    {label:'az',
    w1: 'dal',
    w2: 'chi',
    w3: 'lv',
    w4: 'lar',
    w5: 'lac',
    w6: 'wsh',
    w7: 'dal',
    w8: 'mia',
    w9: 'ne',
    w10: 'no',
    w11: 'dal',
    w12: 'pit',
    w13: 'dal',
    w14: 'cin',
    w15: 'cle'}
    ,
    {label:'det',
    w1: 'sf',
    w2: 'gb',
    w3: 'bal',
    w4: 'chi',
    w5: 'min',
    w6: 'cin',
    w7: 'phi',
    w8: 'lac',
    w9: 'min',
    w10: 'cle',
    w11: 'pit',
    w12: 'chi',
    w13: 'min',
    w14: 'den',
    w15: 'ari'},
    {label:'az',
    w1: 'dal',
    w2: 'chi',
    w3: 'lv',
    w4: 'lar',
    w5: 'lac',
    w6: 'wsh',
    w7: 'dal',
    w8: 'mia',
    w9: 'ne',
    w10: 'no',
    w11: 'dal',
    w12: 'pit',
    w13: 'dal',
    w14: 'cin',
    w15: 'cle'}
    ,
    {label:'det',
    w1: 'sf',
    w2: 'gb',
    w3: 'bal',
    w4: 'chi',
    w5: 'min',
    w6: 'cin',
    w7: 'phi',
    w8: 'lac',
    w9: 'min',
    w10: 'cle',
    w11: 'pit',
    w12: 'chi',
    w13: 'min',
    w14: 'den',
    w15: 'ari'},
    {label:'az',
    w1: 'dal',
    w2: 'chi',
    w3: 'lv',
    w4: 'lar',
    w5: 'lac',
    w6: 'wsh',
    w7: 'dal',
    w8: 'mia',
    w9: 'ne',
    w10: 'no',
    w11: 'dal',
    w12: 'pit',
    w13: 'dal',
    w14: 'cin',
    w15: 'cle'}
    ,
    {label:'det',
    w1: 'sf',
    w2: 'gb',
    w3: 'bal',
    w4: 'chi',
    w5: 'min',
    w6: 'cin',
    w7: 'phi',
    w8: 'lac',
    w9: 'min',
    w10: 'cle',
    w11: 'pit',
    w12: 'chi',
    w13: 'min',
    w14: 'den',
    w15: 'ari'},
    {label:'az',
    w1: 'dal',
    w2: 'chi',
    w3: 'lv',
    w4: 'lar',
    w5: 'lac',
    w6: 'wsh',
    w7: 'dal',
    w8: 'mia',
    w9: 'ne',
    w10: 'no',
    w11: 'dal',
    w12: 'pit',
    w13: 'dal',
    w14: 'cin',
    w15: 'cle'}
    ,
    {label:'det',
    w1: 'sf',
    w2: 'gb',
    w3: 'bal',
    w4: 'chi',
    w5: 'min',
    w6: 'cin',
    w7: 'phi',
    w8: 'lac',
    w9: 'min',
    w10: 'cle',
    w11: 'pit',
    w12: 'chi',
    w13: 'min',
    w14: 'den',
    w15: 'ari'},
    {label:'az',
    w1: 'dal',
    w2: 'chi',
    w3: 'lv',
    w4: 'lar',
    w5: 'lac',
    w6: 'wsh',
    w7: 'dal',
    w8: 'mia',
    w9: 'ne',
    w10: 'no',
    w11: 'dal',
    w12: 'pit',
    w13: 'dal',
    w14: 'cin',
    w15: 'cle'}
    ,
    {label:'det',
    w1: 'sf',
    w2: 'gb',
    w3: 'bal',
    w4: 'chi',
    w5: 'min',
    w6: 'cin',
    w7: 'phi',
    w8: 'lac',
    w9: 'min',
    w10: 'cle',
    w11: 'pit',
    w12: 'chi',
    w13: 'min',
    w14: 'den',
    w15: 'ari'},
    {label:'az',
    w1: 'dal',
    w2: 'chi',
    w3: 'lv',
    w4: 'lar',
    w5: 'lac',
    w6: 'wsh',
    w7: 'dal',
    w8: 'mia',
    w9: 'ne',
    w10: 'no',
    w11: 'dal',
    w12: 'pit',
    w13: 'dal',
    w14: 'cin',
    w15: 'cle'}
    ,
    {label:'det',
    w1: 'sf',
    w2: 'gb',
    w3: 'bal',
    w4: 'chi',
    w5: 'min',
    w6: 'cin',
    w7: 'phi',
    w8: 'lac',
    w9: 'min',
    w10: 'cle',
    w11: 'pit',
    w12: 'chi',
    w13: 'min',
    w14: 'den',
    w15: 'ari'},
    {label:'az',
    w1: 'dal',
    w2: 'chi',
    w3: 'lv',
    w4: 'lar',
    w5: 'lac',
    w6: 'wsh',
    w7: 'dal',
    w8: 'mia',
    w9: 'ne',
    w10: 'no',
    w11: 'dal',
    w12: 'pit',
    w13: 'dal',
    w14: 'cin',
    w15: 'cle'}
    ,
    {label:'det',
    w1: 'sf',
    w2: 'gb',
    w3: 'bal',
    w4: 'chi',
    w5: 'min',
    w6: 'cin',
    w7: 'phi',
    w8: 'lac',
    w9: 'min',
    w10: 'cle',
    w11: 'pit',
    w12: 'chi',
    w13: 'min',
    w14: 'den',
    w15: 'ari'},
    {label:'az',
    w1: 'dal',
    w2: 'chi',
    w3: 'lv',
    w4: 'lar',
    w5: 'lac',
    w6: 'wsh',
    w7: 'dal',
    w8: 'mia',
    w9: 'ne',
    w10: 'no',
    w11: 'dal',
    w12: 'pit',
    w13: 'dal',
    w14: 'cin',
    w15: 'cle'}
    ,
    {label:'det',
    w1: 'sf',
    w2: 'gb',
    w3: 'bal',
    w4: 'chi',
    w5: 'min',
    w6: 'cin',
    w7: 'phi',
    w8: 'lac',
    w9: 'min',
    w10: 'cle',
    w11: 'pit',
    w12: 'chi',
    w13: 'min',
    w14: 'den',
    w15: 'ari'},
    {label:'az',
    w1: 'dal',
    w2: 'chi',
    w3: 'lv',
    w4: 'lar',
    w5: 'lac',
    w6: 'wsh',
    w7: 'dal',
    w8: 'mia',
    w9: 'ne',
    w10: 'no',
    w11: 'dal',
    w12: 'pit',
    w13: 'dal',
    w14: 'cin',
    w15: 'cle'}
    ,
    {label:'det',
    w1: 'sf',
    w2: 'gb',
    w3: 'bal',
    w4: 'chi',
    w5: 'min',
    w6: 'cin',
    w7: 'phi',
    w8: 'lac',
    w9: 'min',
    w10: 'cle',
    w11: 'pit',
    w12: 'chi',
    w13: 'min',
    w14: 'den',
    w15: 'ari'},
    {label:'az',
    w1: 'dal',
    w2: 'chi',
    w3: 'lv',
    w4: 'lar',
    w5: 'lac',
    w6: 'wsh',
    w7: 'dal',
    w8: 'mia',
    w9: 'ne',
    w10: 'no',
    w11: 'dal',
    w12: 'pit',
    w13: 'dal',
    w14: 'cin',
    w15: 'cle'}
    ,
    {label:'det',
    w1: 'sf',
    w2: 'gb',
    w3: 'bal',
    w4: 'chi',
    w5: 'min',
    w6: 'cin',
    w7: 'phi',
    w8: 'lac',
    w9: 'min',
    w10: 'cle',
    w11: 'pit',
    w12: 'chi',
    w13: 'min',
    w14: 'den',
    w15: 'ari'},
    {label:'az',
    w1: 'dal',
    w2: 'chi',
    w3: 'lv',
    w4: 'lar',
    w5: 'lac',
    w6: 'wsh',
    w7: 'dal',
    w8: 'mia',
    w9: 'ne',
    w10: 'no',
    w11: 'dal',
    w12: 'pit',
    w13: 'dal',
    w14: 'cin',
    w15: 'cle'}
    ,
    {label:'det',
    w1: 'sf',
    w2: 'gb',
    w3: 'bal',
    w4: 'chi',
    w5: 'min',
    w6: 'cin',
    w7: 'phi',
    w8: 'lac',
    w9: 'min',
    w10: 'cle',
    w11: 'pit',
    w12: 'chi',
    w13: 'min',
    w14: 'den',
    w15: 'ari'},
    {label:'az',
    w1: 'dal',
    w2: 'chi',
    w3: 'lv',
    w4: 'lar',
    w5: 'lac',
    w6: 'wsh',
    w7: 'dal',
    w8: 'mia',
    w9: 'ne',
    w10: 'no',
    w11: 'dal',
    w12: 'pit',
    w13: 'dal',
    w14: 'cin',
    w15: 'cle'}
    ,
    {label:'det',
    w1: 'sf',
    w2: 'gb',
    w3: 'bal',
    w4: 'chi',
    w5: 'min',
    w6: 'cin',
    w7: 'phi',
    w8: 'lac',
    w9: 'min',
    w10: 'cle',
    w11: 'pit',
    w12: 'chi',
    w13: 'min',
    w14: 'den',
    w15: 'ari'},
    

]
